version: '3'

services:
  redis:
    container_name: redis-mb
    image: "redis:latest"
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: api-mb
    env_file: .env
    command: sh -c " pytest -v && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    depends_on:
      - redis